export const reportsTypeMap = {
    "all": "Alle Typen",
    "attendance": "Anwesenheit",
    "finance": "Finanzbericht",
    "event": "Veranstaltung",
    "annualReport": "Jahresbericht",
    "protocol": "Protokoll",
    "birthday": "Geburtstag",
    "death": "Todesfall",
    "anniversary": "Vereinsjubiläum",
    "internalEvent": "Vereinsveranstaltung",
    "weeding": "Hochzeit",
    "other": "Sonstiges",
    // Reversed
    "Alle Typen": "all",
    "Anwesenheit": "attendance",
    "Finanzbericht": "finance",
    "Veranstaltung": "event",
    "Jahresbericht": "annualReport",
    "Protokoll": "protocol",
    "Geburtstag": "birthday",
    "Todesfall": "death",
    "Vereinsjubiläum": "anniversary",
    "Vereinsveranstaltung": "internalEvent",
    "Hochzeit": "weeding",
    "Sonstiges": "other",
}