spring:
  application:
    name: gvw-backend
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 50MB
  mail:
    host: smtp.strato.de
    port: 465
    username: ${GVW_MAIL_USERNAME}
    password: ${GVW_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

server:
  port: ${GVW_PORT}

couchdb:
  url: http://localhost:5984
  user: ${GVW_DB_USERNAME}
  password: ${GVW_DB_PASSWORD}

jwt:
  secret: "${GVW_JWT_SECRET}"
  expiration-days: 7
