spring:
  application:
    name: gvw-backend

server:
  port: 3500

couchdb:
  url: http://localhost:5984
  user: ${GVW_DB_USERNAME}
  password: ${GVW_DB_PASSWORD}

jwt:
  secret: "${GVW_JWT_SECRET}"
  expiration-days: 7
