export const marginMap = {
    "0": "mt-0",
    "": "mt-0",
    "1": "mt-1",
    "2": "mt-2",
    "3": "mt-3",
    "4": "mt-4",
    "5": "mt-5",
    "6": "mt-6",
    "7": "mt-7",
    "8": "mt-8",
    "9": "mt-9",
    "10": "mt-10",
};

export const paddingMap = {
    "0": "p-0",
    "": "p-0",
    "1": "p-1",
    "2": "p-2",
    "3": "p-3",
    "4": "p-4",
    "5": "p-5",
    "6": "p-6",
    "7": "p-7",
    "8": "p-8",
    "9": "p-9",
    "10": "p-10",
};

export const justifyMap = {
    "justify-start": "justify-start",
    "justify-end": "justify-end",
    "justify-center": "justify-center",
    "justify-between": "justify-between",
    "justify-around": "justify-around",
    "justify-evenly": "justify-evenly",
    "justify-stretch": "justify-stretch",
    "justify-items-start": "justify-items-start",
    "justify-items-end": "justify-items-end",
    "justify-items-center": "justify-items-center",
    "justify-items-stretch": "justify-items-stretch",
    "justify-self-auto": "justify-self-auto",
    "justify-self-start": "justify-self-start",
    "justify-self-end": "justify-self-end",
    "justify-self-center": "justify-self-center",
    "justify-self-stretch": "justify-self-stretch",
    "": "justify-start",
};